name = "StrataBoole"
version = "0.1.0"
defaultTargets = ["StrataBoole"]
testDriver = "StrataBooleTest"

[[require]]
name = "Strata"
path = ".."

[[lean_lib]]
name = "StrataBoole"

[[lean_lib]]
name = "StrataBooleTest"
