name = "StrataBoole"
version = "0.1.0"
defaultTargets = ["StrataBoole"]
testDriver = "StrataBooleTest"

[[require]]
name = "Strata"
git = "https://github.com/kondylidou/Strata"
rev = "fix/batch-unknown-candidate-model"

[[lean_lib]]
name = "StrataBoole"

[[lean_lib]]
name = "StrataBooleTest"
