/-
  Copyright Strata Contributors

  SPDX-License-Identifier: Apache-2.0 OR MIT
-/
import StrataBooleTest.array_2d
import StrataBooleTest.array_assignment
import StrataBooleTest.bit_vectors
import StrataBooleTest.code_expression
import StrataBooleTest.demo
import StrataBooleTest.deterministic
import StrataBooleTest.find_max
import StrataBooleTest.find_max_verus
import StrataBooleTest.format_program
import StrataBooleTest.function_definitions
import StrataBooleTest.global_readonly_call
import StrataBooleTest.grammar_extensions
import StrataBooleTest.insertion_sort
import StrataBooleTest.loop_simple
import StrataBooleTest.procedure_signatures
import StrataBooleTest.square_matrix_multiply
import StrataBooleTest.stack_array_based
import StrataBooleTest.string_operators
import StrataBooleTest.top_level_block_selection
import StrataBooleTest.verification_coverage
import StrataBooleTest.FeatureRequests.abstract_types_and_stubs
import StrataBooleTest.FeatureRequests.bitvector_ops
import StrataBooleTest.FeatureRequests.bitvector_proof_mode
import StrataBooleTest.FeatureRequests.choose_operator
import StrataBooleTest.FeatureRequests.datatypes_and_selectors
import StrataBooleTest.FeatureRequests.decreases_metadata
import StrataBooleTest.FeatureRequests.early_return
import StrataBooleTest.FeatureRequests.higher_order_encoding
import StrataBooleTest.FeatureRequests.horner_poly_eval
import StrataBooleTest.FeatureRequests.lambda_closure
import StrataBooleTest.FeatureRequests.map_extensionality
import StrataBooleTest.FeatureRequests.mutual_recursion
import StrataBooleTest.FeatureRequests.nat_int_boundary
import StrataBooleTest.FeatureRequests.opaque_reveal_hide
import StrataBooleTest.FeatureRequests.option_matches
import StrataBooleTest.FeatureRequests.overflow_guard
import StrataBooleTest.FeatureRequests.reveal_with_fuel
import StrataBooleTest.FeatureRequests.seq_slicing
import StrataBooleTest.FeatureRequests.struct_field_access
import StrataBooleTest.FeatureRequests.trait_spec_methods
import StrataBooleTest.FeatureRequests.widening_casts
