name: Build

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

jobs:
  build_and_test_lean:
    name: Build and test Lean
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build and test
        uses: leanprover/lean-action@v1
        with:
          use-github-cache: false
          test: true
